services:
  - type: static
    name: erick-second-site
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
